version: "3.4"

services:
  store_service:
    image: store_service
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000
